version: "3.7"
services:
  postgresql:
    image: postgres:15
    container_name: "db-postgresql"
    # раскоменитить для сохранения БД
#    volumes:
#      - ./docker/postgresql/data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=parser_db
      - POSTGRES_USER=parser_user
      - POSTGRES_PASSWORD=parser_password
    ports:
      - "5432:5432"
