version: "3.7"
services:
  postgresql:
    image: postgres:15-alpine
    container_name: "db-postgresql"
    volumes:
      - ./docker/postgresql/data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=parser_db
      - POSTGRES_USER=parser_user
      - POSTGRES_PASSWORD=parser_password
    ports:
      - "5433:5432"
  rabbitMq:
    image: rabbitmq:3.9-alpine
    expose:
      - "5672" # Основной порт для очереди из под приложения (AMQP)
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    volumes:
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq
  backend-java-app:
    build:
      context: .
    container_name: "java-backend-app"
    depends_on:
      - postgresql
      - rabbitMq
    ports:
      - "80:80"
    volumes:
      - ./files/xlsx/:/app/files/xlsx/
