version: "3.7"
services:
  postgresql:
    image: postgres:15
    container_name: "db-postgresql"
    # раскоменитить для сохранения БД
#    volumes:
#      - ./docker/postgresql/data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=parser_db
      - POSTGRES_USER=parser_user
      - POSTGRES_PASSWORD=parser_password
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: redis
    expose:
      - "6379"
    restart: always
  rabbitMq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672" # Основной порт для очереди из под приложения (AMQP)
      - "15672:15672" # Порт для интерфейса
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
#    volumes:
#      - ./docker/rabbitmq/data/:/var/lib/rabbitmq

